### ISSUE TITLE
Targeted commands not working with pandoc

### ISSUE THREAD

**Issue by ererkka** [didierverna/fixme#3] opened 2018-01-19 12:19 UTC
The targeted text of the starred versions of FiXme notes do not show when converting the LaTeX using [pandoc](https://pandoc.org/). The targeted text is always just missing, even if in final mode.  
I’ve tried converting to docx, plain text and html. I don’t know if this should be a pandoc issue. 

An example document:

    % untitled.tex
    \documentclass[draft]{article}
    \usepackage{fixme}
    \begin{document}
    Some text.
    
    Some more text. \fxnote{A note}
    
    \fxnote*{Targeted note}{Even more text}
    \end{document}

Converting with pandoc to plain text:

    pandoc -t plain -o untitled.txt untitled.tex

**Comment by didierverna** [comment] 2018-12-22 18:40
Hello,

I could reproduce the problem, but I don't think it's FiXme's fault. When running pandoc --verbose to generate a PDF, the output shows that pandoc can't locate fixme.sty, and skips all FiXme commands. So you don't see the notes, but neither the targeted text, because it's part of the command. I tried putting fixme.sty in the same directory as the test file, but then some other errors occur.

I'm not a pandoc user so I can't tell what's wrong, but I'm pretty confident that FiXme is not the culprit, so I'm closing this.

Good luck!

**Closed by didierverna** 2018-12-22 18:40 UTC
